### ISSUE TITLE
Netbox Returned Record Limit

### ISSUE THREAD

**Issue by goombah88** [rakelord/PSNetboxFunctions#1]
Since Netbox is only able to return 1000 records at a time it would make sense to remove the hard-coded "limit=0" in PSNetboxFunctions.psm1. Having this value hard-coded in the code prevent anyone from being able to set an arbitrary limit. I recommend removing "?limit=0" for versatility.

If you're curious how I overcame the 1000 record limit...I used offset to create pagination. I needed a way to dump entire tables from NB to CSV as a disaster recovery last resort.

# Example
# Get-NetboxObjects -APIEndpoint "/api/virtualization/virtual-machines/?limit=1000&offset=0" -LogToFile "False" | export-csv -Append vms.csv
# Get-NetboxObjects -APIEndpoint "/api/virtualization/virtual-machines/?limit=1000&offset=1000" -LogToFile "False" | export-csv -Append vms.csv
# Get-NetboxObjects -APIEndpoint "/api/virtualization/virtual-machines/?limit=1000&offset=2000" -LogToFile "False" | export-csv -Append vms.csv

This is what I changed in PSNetboxFunctions.psm1
        # $uri = "$($netboxUrl)$($APIEndpoint)?limit=0"
        $uri = "$($netboxUrl)$($APIEndpoint)"

**Comment by goombah88** [comment]
Sorry for the crazy fontage, my markdown is weak at best.

**Comment by rekanized** [comment]
Hi @goombah88!
Thanks for you report!

I see what you mean, do not really remember why I set that limit in the first place.
I will remove it when I start work again =)!

The current function should already return every object (past 1000), it checks for .results value in the return and if it exists it uses the url from .next and returns that within the returned object.
Is this not working for you?
Or are you trying to return a specific page of 1000s?

**Comment by goombah88** [comment]
I'm trying to dump each table in Netbox to a CSV file for disaster recovery and whenever I try to pull all records with limit=0 I get the error and only 1000 records returned. Other colleagues have had the same experience when dealing with Netbox. I'm told even the pynetbox python library has the same issue. But by pairing up filter and limit I was able to create a poor-man's pagination to get all records from all tables.

**Comment by goombah88** [comment]
I tried leaving the limit=0 in there and just using the offset at 0, 1000, 2000, etc. and each loop compounded the loop before it. I have 10357 rows in the /dcim/devices table so it'll take 11 loops of 1000 each to dump all rows. After it was done I have 11 separate entries for ID 10133 in the CSV file. That's why I have to set limit=1000 in conjunction with the offset to accomplish my task.

**Comment by rekanized** [comment]
This is now changed in main code =)
limit=1000 is removed
